// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'page-wrap': string;
  'pageWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
