// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aboutWrapper': string;
  'blueColumn': string;
  'column': string;
  'greenColumn': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
