// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aboutImg': string;
  'aboutWrapper': string;
  'blueColumn': string;
  'column': string;
  'devImage': string;
  'greenColumn': string;
  'orangeColumn': string;
  'purpleRow': string;
  'row': string;
  'spacerRow': string;
}
export const cssExports: CssExports;
export default cssExports;
