// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aboutImg': string;
  'aboutImgLogo': string;
  'aboutLinks': string;
  'aboutWrapper': string;
  'column': string;
  'devImage': string;
  'greenColumn': string;
  'imageColumn': string;
  'imageColumnMobile': string;
  'linkOne': string;
  'resourceLink': string;
  'row': string;
  'textColumn': string;
  'textColumnOne': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
