// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'failToFindCard': string;
  'failToFindImage': string;
}
export const cssExports: CssExports;
export default cssExports;
