// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'image': string;
  'link': string;
  'salary': string;
}
export const cssExports: CssExports;
export default cssExports;
