// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'job-card': string;
  'jobCard': string;
}
export const cssExports: CssExports;
export default cssExports;
