// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'search': string;
  'searchIcon': string;
  'searchInput': string;
}
export const cssExports: CssExports;
export default cssExports;
