// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'menu': string;
  'menuButton': string;
  'menuIcon': string;
  'menuToggle': string;
  'navItem': string;
  'navLogoImage': string;
  'navLogoText': string;
  'navMenu': string;
  'navbar': string;
}
export const cssExports: CssExports;
export default cssExports;
