// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'authWrapper': string;
  'form': string;
  'formButton': string;
  'formDescription': string;
  'formGroup': string;
  'formInput': string;
  'formLabel': string;
  'formTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
