// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menu': string;
  'menuButton': string;
  'menuToggle': string;
  'navItemMobile': string;
  'navLinkMobile': string;
  'opacityLayer': string;
}
export const cssExports: CssExports;
export default cssExports;
