// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loadingAnimationWrapper': string;
  'loadingSpinner': string;
}
export const cssExports: CssExports;
export default cssExports;
